---

name: Molecule Test

on:
  schedule:
  - cron: "0 0 * * *"
  push:
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:


jobs:
  default-scenario:
    name: Molecule test - default scenario
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the molecule test
        run: molecule test -s default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          options: parallel
